changesetBaseRefs:
  - latest
  - origin/latest
  - next
  - origin/next

compressionLevel: mixed

enableGlobalCache: false

enableTransparentWorkspaces: false

yarnPath: .yarn/releases/yarn-4.9.2.cjs
